### ISSUE TITLE
I get this Error When I try to import .npz  file

### ISSUE THREAD

**Issue by hhhlllyyy** [vltmedia/QuickMocap-BlenderAddon#5]
![1640858157(1)](https://user-images.githubusercontent.com/79896898/147741139-cc6ee336-a0a5-4763-9863-bb7bb695e059.png)

.fbx model path has been set
blender version:3.0.0
![1640858329(1)](https://user-images.githubusercontent.com/79896898/147741378-a7e85623-8855-4d2f-bbae-50fe996c161e.png)

How can I solve this problem?
thank you！

**Comment by lclayton2002** [comment]
If you used a zip file download of QuickMocap I had to change the following in the helpers/smpl_import.py file
#addon_prefs = preferences.addons['QuickMocap'].preferences
addon_prefs = preferences.addons['QuickMocap-BlenderAddon-master'].preferences

It then worked.

**Comment by vltmedia** [comment]
Sorry for the super late reply, I implemented the fix by @lclayton2002  along with adding other conditional states just incase. 
Closing the issue now.
